# fly.toml app configuration file generated for backend-divine-bird-6088 on 2025-01-05T01:15:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-divine-bird-6088'
primary_region = 'lax'
console_command = '/code/manage.py shell'

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "gauchoguide.settings"
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  #auto_stop_machines = 'stop'
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
